import type { Metadata } from "next";
import "./globals.css";
import BoxesBackground from "./components/ui/boxes-background";

export const metadata: Metadata = {
  title: "Rozak's Portofolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="min-h-screen w-full bg-black relative">
          <div className="fixed inset-0 z-0">
          <BoxesBackground />
          </div>
          <div className="relative z-20">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}